# Generated by Django 3.0 on 2023-08-13 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_p', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horaEntrada', models.TimeField()),
                ('horaSalida', models.TimeField()),
                ('horasExtras', models.IntegerField()),
                ('fk_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_p.Clinica')),
            ],
            options={
                'verbose_name': 'Jormada',
                'verbose_name_plural': 'Jornadas',
            },
        ),
        migrations.DeleteModel(
            name='Jormada',
        ),
    ]
